build:
  version: "1.0"

loans:
  message: "Hey, welcome to IJP related prod APIs "
  contactDetails:
    name: "Joey - Product Owner"
    email: "joey@ijp.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
